---
#Tasks install and start "glusterd" service

- name: Install GlusterFS repository
  yum: 
    name: centos-release-gluster
    state: latest
  register: gluster_repo

- name: Install GlusterFS client
  yum: 
    name: glusterfs-client
    state: latest
  when: gluster_repo|succeeded
  
- name: Create mount Point Folder
  file:
    path: "{{gluster_mount_dir}}"
    state: directory
    owner: root
    group: root
    mode: 0775
  register: folder_created

- name: Edit fstab and mount the XFS volume
  mount:
    name: "{{gluster_mount_dir}}"
    src: "{{groups.all[0]}}:/{{gluster_volume_name}}"
    fstype: glusterfs
    opts: "noatime"
    state: mounted
